type Costumer{
"""
-type ID 
"""
_id: ID!         
"""
-type String
"""
firstName: String  
"""
-type String
"""
lastName: String   
"""
-type DNI
"""
dni: DNI
"""
-type String
"""
address: String    
"""
-type Int
"""
totalVisits: Int

"""
-created
"""

created: DateTime    
"""
-updated
"""

updated: DateTime    
}

type EdgeCostumer{
"""
-bsonOmmit
"""
edges: [Costumer]
"""
-bsonOmmit
"""
pageInfo: PageInfo

}